/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.AST.Program;
import compiler.Lexer.Lexer;
import compiler.Lexer.Symbol;
import compiler.Parser.Parser;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

public class Compiler {

    public static void main(String[] args) {
        if (args.length != 2) {
            System.exit(1);
        }

        String mode = args[0];
        String path = args[1];

        try (Reader r = new BufferedReader(new FileReader(path))) {

            if (mode.equals("-lexer")) {
                Lexer lexer = new Lexer(r);

                while (true) {
                    Symbol s = lexer.getNextSymbol();
                    System.out.println(s); 

                    if (s.type == Symbol.Type.END_FILE) {
                        break;
                    }
                }
                return;
            }

            if (mode.equals("-parser")) {
                Lexer lexer = new Lexer(r);
                Parser parser = new Parser(lexer);
                Program ast = parser.getAST();

                ast.printTree();
                return;
            }

            System.err.println("Unknown option: " + mode);
            System.err.println("Use -lexer or -parser");
            System.exit(1);

        } catch (RuntimeException e) {
            System.err.println(e.getMessage());
            System.exit(1);
        } catch (IOException e) {
            System.err.println("I/O error: " + e.getMessage());
            System.exit(1);
        }
    }
}